#! /bin/sh
if ! [ -e cos_info.txt ]; then
	curl 'https://timetable.nctu.edu.tw/?r=main/get_cos_list' --data  'm_acy=107&m_sem=1&m_degree=3&m_dep_id=17&m_group=**&m_grade=**&m_class=**&m_option=**&m_crsname=**&m_teaname=**&m_cos_id=**&m_cos_code=**&m_crstime=**&m_crsoutline=**&m_costype=**' | sed 's#","#"\'$'\n"#g' | grep 'cos_ename\|cos_time' > cos_info.txt;
fi

#format class information
cat 'cos_info.txt' | sed -e 'N; s#\n# #' -e 's# #_#g' | \
sed -e 's#"cos_time":"##g' -e 's#cos_ename":"##' -e 's#"_"#-#g' | sed -e 's#"##g' > format_cos.txt

#convert to dialog format
if ! [ -e class_state.txt ]; then 
  cat 'format_cos.txt' | awk '{print NR, "\"" $0 "\"", "off"}' > class_state.txt
  for i in `seq 1 5`;do
    

  done
fi


# change calss_state by dialog
change_stat=$(dialog --buildlist "Add class" 70 90 20 `cat class_state.txt` --output-fd 1)
for i in $change_stat;do
  #echo $i;
  
  sed -e "$i s# off# on#g" class_state.txt > class_state.txt.tmp
  cat class_state.txt.tmp > class_state.txt
done
#cat class_state.tx

#class collision


