#! /bin/sh
if ! [ -e cos_info.txt ]; then
	curl 'https://timetable.nctu.edu.tw/?r=main/get_cos_list' --data  'm_acy=107&m_sem=1&m_degree=3&m_dep_id=17&m_group=**&m_grade=**&m_class=**&m_option=**&m_crsname=**&m_teaname=**&m_cos_id=**&m_cos_code=**&m_crstime=**&m_crsoutline=**&m_costype=**' | sed 's#","#"\'$'\n"#g' | grep 'cos_ename\|cos_time' > cos_info.txt;
fi

#format class information
cat 'cos_info.txt' | sed 'N; s#\n# #' | \
sed -e 's#"cos_time":"##g' -e 's#cos_ename":"##' -e 's#" "# - #g' | sed -e 's#"##g' > format_cos.txt

#convert to dialog format
input_to_add=$(cat 'format_cos.txt' | awk '{print "f"NR, "\"" $0 "\"", "off"}')

dialog --buildlist "Add class" 50 60 20 `$input_to_add`

